# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: hermes/keryx/v1/agent.proto
# Protobuf Python Version: 7.35.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    0,
    '',
    'hermes/keryx/v1/agent.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from hermes.keryx.v1 import common_pb2 as hermes_dot_keryx_dot_v1_dot_common__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1bhermes/keryx/v1/agent.proto\x12\x0fhermes.keryx.v1\x1a\x1chermes/keryx/v1/common.proto\"\xd1\x03\n\rAgentManifest\x12*\n\x08\x61gent_id\x18\x01 \x01(\x0b\x32\x18.hermes.keryx.v1.AgentId\x12(\n\x07node_id\x18\x02 \x01(\x0b\x32\x17.hermes.keryx.v1.NodeId\x12\x0c\n\x04name\x18\x03 \x01(\t\x12\x14\n\x0c\x64isplay_name\x18\x04 \x01(\t\x12\x13\n\x0b\x64\x65scription\x18\x05 \x01(\t\x12\x0f\n\x07version\x18\x06 \x01(\t\x12\x0f\n\x07runtime\x18\x07 \x01(\t\x12\x33\n\x0c\x63\x61pabilities\x18\x08 \x03(\x0b\x32\x1d.hermes.keryx.v1.CapabilityId\x12:\n\x06labels\x18\t \x03(\x0b\x32*.hermes.keryx.v1.AgentManifest.LabelsEntry\x12>\n\x08metadata\x18\n \x03(\x0b\x32,.hermes.keryx.v1.AgentManifest.MetadataEntry\x1a-\n\x0bLabelsEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\x1a/\n\rMetadataEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'hermes.keryx.v1.agent_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_AGENTMANIFEST_LABELSENTRY']._loaded_options = None
  _globals['_AGENTMANIFEST_LABELSENTRY']._serialized_options = b'8\001'
  _globals['_AGENTMANIFEST_METADATAENTRY']._loaded_options = None
  _globals['_AGENTMANIFEST_METADATAENTRY']._serialized_options = b'8\001'
  _globals['_AGENTMANIFEST']._serialized_start=79
  _globals['_AGENTMANIFEST']._serialized_end=544
  _globals['_AGENTMANIFEST_LABELSENTRY']._serialized_start=450
  _globals['_AGENTMANIFEST_LABELSENTRY']._serialized_end=495
  _globals['_AGENTMANIFEST_METADATAENTRY']._serialized_start=497
  _globals['_AGENTMANIFEST_METADATAENTRY']._serialized_end=544
# @@protoc_insertion_point(module_scope)
