# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: hermes/keryx/v1/common.proto
# Protobuf Python Version: 7.35.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    0,
    '',
    'hermes/keryx/v1/common.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1chermes/keryx/v1/common.proto\x12\x0fhermes.keryx.v1\"\x17\n\x06NodeId\x12\r\n\x05value\x18\x01 \x01(\t\"\x18\n\x07\x41gentId\x12\r\n\x05value\x18\x01 \x01(\t\"\x1d\n\x0c\x43\x61pabilityId\x12\r\n\x05value\x18\x01 \x01(\t\"\x17\n\x06TaskId\x12\r\n\x05value\x18\x01 \x01(\t\"\x1e\n\rCorrelationId\x12\r\n\x05value\x18\x01 \x01(\t\"\x1f\n\x0eIdempotencyKey\x12\r\n\x05value\x18\x01 \x01(\t\"\x1a\n\tAttemptId\x12\r\n\x05value\x18\x01 \x01(\t\"\x18\n\x07LeaseId\x12\r\n\x05value\x18\x01 \x01(\t\"\x1b\n\nArtifactId\x12\r\n\x05value\x18\x01 \x01(\t\"\x1c\n\tTimestamp\x12\x0f\n\x07unix_ms\x18\x01 \x01(\x03\"7\n\x0bVersionInfo\x12\x10\n\x08protocol\x18\x01 \x01(\t\x12\x16\n\x0eimplementation\x18\x02 \x01(\t\"\x97\x01\n\tErrorInfo\x12\x0c\n\x04\x63ode\x18\x01 \x01(\t\x12\x0f\n\x07message\x18\x02 \x01(\t\x12:\n\x08metadata\x18\x03 \x03(\x0b\x32(.hermes.keryx.v1.ErrorInfo.MetadataEntry\x1a/\n\rMetadataEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'hermes.keryx.v1.common_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_ERRORINFO_METADATAENTRY']._loaded_options = None
  _globals['_ERRORINFO_METADATAENTRY']._serialized_options = b'8\001'
  _globals['_NODEID']._serialized_start=49
  _globals['_NODEID']._serialized_end=72
  _globals['_AGENTID']._serialized_start=74
  _globals['_AGENTID']._serialized_end=98
  _globals['_CAPABILITYID']._serialized_start=100
  _globals['_CAPABILITYID']._serialized_end=129
  _globals['_TASKID']._serialized_start=131
  _globals['_TASKID']._serialized_end=154
  _globals['_CORRELATIONID']._serialized_start=156
  _globals['_CORRELATIONID']._serialized_end=186
  _globals['_IDEMPOTENCYKEY']._serialized_start=188
  _globals['_IDEMPOTENCYKEY']._serialized_end=219
  _globals['_ATTEMPTID']._serialized_start=221
  _globals['_ATTEMPTID']._serialized_end=247
  _globals['_LEASEID']._serialized_start=249
  _globals['_LEASEID']._serialized_end=273
  _globals['_ARTIFACTID']._serialized_start=275
  _globals['_ARTIFACTID']._serialized_end=302
  _globals['_TIMESTAMP']._serialized_start=304
  _globals['_TIMESTAMP']._serialized_end=332
  _globals['_VERSIONINFO']._serialized_start=334
  _globals['_VERSIONINFO']._serialized_end=389
  _globals['_ERRORINFO']._serialized_start=392
  _globals['_ERRORINFO']._serialized_end=543
  _globals['_ERRORINFO_METADATAENTRY']._serialized_start=496
  _globals['_ERRORINFO_METADATAENTRY']._serialized_end=543
# @@protoc_insertion_point(module_scope)
