# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from hermes.keryx.v1 import daemon_pb2 as hermes_dot_keryx_dot_v1_dot_daemon__pb2

GRPC_GENERATED_VERSION = '1.82.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in hermes/keryx/v1/daemon_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class KeryxDaemonStub:
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Status = channel.unary_unary(
                '/hermes.keryx.v1.KeryxDaemon/Status',
                request_serializer=hermes_dot_keryx_dot_v1_dot_daemon__pb2.StatusRequest.SerializeToString,
                response_deserializer=hermes_dot_keryx_dot_v1_dot_daemon__pb2.StatusResponse.FromString,
                _registered_method=True)
        self.Doctor = channel.unary_unary(
                '/hermes.keryx.v1.KeryxDaemon/Doctor',
                request_serializer=hermes_dot_keryx_dot_v1_dot_daemon__pb2.DoctorRequest.SerializeToString,
                response_deserializer=hermes_dot_keryx_dot_v1_dot_daemon__pb2.DoctorResponse.FromString,
                _registered_method=True)
        self.Liveness = channel.unary_unary(
                '/hermes.keryx.v1.KeryxDaemon/Liveness',
                request_serializer=hermes_dot_keryx_dot_v1_dot_daemon__pb2.LivenessRequest.SerializeToString,
                response_deserializer=hermes_dot_keryx_dot_v1_dot_daemon__pb2.LivenessResponse.FromString,
                _registered_method=True)
        self.Readiness = channel.unary_unary(
                '/hermes.keryx.v1.KeryxDaemon/Readiness',
                request_serializer=hermes_dot_keryx_dot_v1_dot_daemon__pb2.ReadinessRequest.SerializeToString,
                response_deserializer=hermes_dot_keryx_dot_v1_dot_daemon__pb2.ReadinessResponse.FromString,
                _registered_method=True)
        self.SubmitTask = channel.unary_unary(
                '/hermes.keryx.v1.KeryxDaemon/SubmitTask',
                request_serializer=hermes_dot_keryx_dot_v1_dot_daemon__pb2.SubmitTaskRequest.SerializeToString,
                response_deserializer=hermes_dot_keryx_dot_v1_dot_daemon__pb2.SubmitTaskResponse.FromString,
                _registered_method=True)
        self.SubmitRemoteTask = channel.unary_unary(
                '/hermes.keryx.v1.KeryxDaemon/SubmitRemoteTask',
                request_serializer=hermes_dot_keryx_dot_v1_dot_daemon__pb2.SubmitRemoteTaskRequest.SerializeToString,
                response_deserializer=hermes_dot_keryx_dot_v1_dot_daemon__pb2.SubmitTaskResponse.FromString,
                _registered_method=True)
        self.GetTaskResult = channel.unary_unary(
                '/hermes.keryx.v1.KeryxDaemon/GetTaskResult',
                request_serializer=hermes_dot_keryx_dot_v1_dot_daemon__pb2.GetTaskResultRequest.SerializeToString,
                response_deserializer=hermes_dot_keryx_dot_v1_dot_daemon__pb2.GetTaskResultResponse.FromString,
                _registered_method=True)
        self.ClaimNextResultDelivery = channel.unary_unary(
                '/hermes.keryx.v1.KeryxDaemon/ClaimNextResultDelivery',
                request_serializer=hermes_dot_keryx_dot_v1_dot_daemon__pb2.ClaimNextResultDeliveryRequest.SerializeToString,
                response_deserializer=hermes_dot_keryx_dot_v1_dot_daemon__pb2.ClaimNextResultDeliveryResponse.FromString,
                _registered_method=True)
        self.AckResultDelivery = channel.unary_unary(
                '/hermes.keryx.v1.KeryxDaemon/AckResultDelivery',
                request_serializer=hermes_dot_keryx_dot_v1_dot_daemon__pb2.AckResultDeliveryRequest.SerializeToString,
                response_deserializer=hermes_dot_keryx_dot_v1_dot_daemon__pb2.AckResultDeliveryResponse.FromString,
                _registered_method=True)
        self.FailResultDelivery = channel.unary_unary(
                '/hermes.keryx.v1.KeryxDaemon/FailResultDelivery',
                request_serializer=hermes_dot_keryx_dot_v1_dot_daemon__pb2.FailResultDeliveryRequest.SerializeToString,
                response_deserializer=hermes_dot_keryx_dot_v1_dot_daemon__pb2.FailResultDeliveryResponse.FromString,
                _registered_method=True)
        self.IngestRemoteResult = channel.unary_unary(
                '/hermes.keryx.v1.KeryxDaemon/IngestRemoteResult',
                request_serializer=hermes_dot_keryx_dot_v1_dot_daemon__pb2.IngestRemoteResultRequest.SerializeToString,
                response_deserializer=hermes_dot_keryx_dot_v1_dot_daemon__pb2.IngestRemoteResultResponse.FromString,
                _registered_method=True)
        self.ClaimTask = channel.unary_unary(
                '/hermes.keryx.v1.KeryxDaemon/ClaimTask',
                request_serializer=hermes_dot_keryx_dot_v1_dot_daemon__pb2.ClaimTaskRequest.SerializeToString,
                response_deserializer=hermes_dot_keryx_dot_v1_dot_daemon__pb2.ClaimTaskResponse.FromString,
                _registered_method=True)
        self.ClaimNextTask = channel.unary_unary(
                '/hermes.keryx.v1.KeryxDaemon/ClaimNextTask',
                request_serializer=hermes_dot_keryx_dot_v1_dot_daemon__pb2.ClaimNextTaskRequest.SerializeToString,
                response_deserializer=hermes_dot_keryx_dot_v1_dot_daemon__pb2.ClaimNextTaskResponse.FromString,
                _registered_method=True)
        self.Heartbeat = channel.unary_unary(
                '/hermes.keryx.v1.KeryxDaemon/Heartbeat',
                request_serializer=hermes_dot_keryx_dot_v1_dot_daemon__pb2.HeartbeatRequest.SerializeToString,
                response_deserializer=hermes_dot_keryx_dot_v1_dot_daemon__pb2.HeartbeatResponse.FromString,
                _registered_method=True)
        self.CompleteTask = channel.unary_unary(
                '/hermes.keryx.v1.KeryxDaemon/CompleteTask',
                request_serializer=hermes_dot_keryx_dot_v1_dot_daemon__pb2.CompleteTaskRequest.SerializeToString,
                response_deserializer=hermes_dot_keryx_dot_v1_dot_daemon__pb2.CompleteTaskResponse.FromString,
                _registered_method=True)
        self.FailTask = channel.unary_unary(
                '/hermes.keryx.v1.KeryxDaemon/FailTask',
                request_serializer=hermes_dot_keryx_dot_v1_dot_daemon__pb2.FailTaskRequest.SerializeToString,
                response_deserializer=hermes_dot_keryx_dot_v1_dot_daemon__pb2.FailTaskResponse.FromString,
                _registered_method=True)
        self.CancelTask = channel.unary_unary(
                '/hermes.keryx.v1.KeryxDaemon/CancelTask',
                request_serializer=hermes_dot_keryx_dot_v1_dot_daemon__pb2.CancelTaskRequest.SerializeToString,
                response_deserializer=hermes_dot_keryx_dot_v1_dot_daemon__pb2.CancelTaskResponse.FromString,
                _registered_method=True)
        self.PutArtifact = channel.unary_unary(
                '/hermes.keryx.v1.KeryxDaemon/PutArtifact',
                request_serializer=hermes_dot_keryx_dot_v1_dot_daemon__pb2.PutArtifactRequest.SerializeToString,
                response_deserializer=hermes_dot_keryx_dot_v1_dot_daemon__pb2.PutArtifactResponse.FromString,
                _registered_method=True)
        self.GetArtifact = channel.unary_unary(
                '/hermes.keryx.v1.KeryxDaemon/GetArtifact',
                request_serializer=hermes_dot_keryx_dot_v1_dot_daemon__pb2.GetArtifactRequest.SerializeToString,
                response_deserializer=hermes_dot_keryx_dot_v1_dot_daemon__pb2.GetArtifactResponse.FromString,
                _registered_method=True)
        self.ListArtifacts = channel.unary_unary(
                '/hermes.keryx.v1.KeryxDaemon/ListArtifacts',
                request_serializer=hermes_dot_keryx_dot_v1_dot_daemon__pb2.ListArtifactsRequest.SerializeToString,
                response_deserializer=hermes_dot_keryx_dot_v1_dot_daemon__pb2.ListArtifactsResponse.FromString,
                _registered_method=True)
        self.DeleteArtifact = channel.unary_unary(
                '/hermes.keryx.v1.KeryxDaemon/DeleteArtifact',
                request_serializer=hermes_dot_keryx_dot_v1_dot_daemon__pb2.DeleteArtifactRequest.SerializeToString,
                response_deserializer=hermes_dot_keryx_dot_v1_dot_daemon__pb2.DeleteArtifactResponse.FromString,
                _registered_method=True)
        self.SendTask = channel.unary_unary(
                '/hermes.keryx.v1.KeryxDaemon/SendTask',
                request_serializer=hermes_dot_keryx_dot_v1_dot_daemon__pb2.SendTaskRequest.SerializeToString,
                response_deserializer=hermes_dot_keryx_dot_v1_dot_daemon__pb2.SendTaskResponse.FromString,
                _registered_method=True)
        self.ListPeers = channel.unary_unary(
                '/hermes.keryx.v1.KeryxDaemon/ListPeers',
                request_serializer=hermes_dot_keryx_dot_v1_dot_daemon__pb2.ListPeersRequest.SerializeToString,
                response_deserializer=hermes_dot_keryx_dot_v1_dot_daemon__pb2.ListPeersResponse.FromString,
                _registered_method=True)
        self.DiscoverSkills = channel.unary_unary(
                '/hermes.keryx.v1.KeryxDaemon/DiscoverSkills',
                request_serializer=hermes_dot_keryx_dot_v1_dot_daemon__pb2.DiscoverSkillsRequest.SerializeToString,
                response_deserializer=hermes_dot_keryx_dot_v1_dot_daemon__pb2.DiscoverSkillsResponse.FromString,
                _registered_method=True)


class KeryxDaemonServicer:
    """Missing associated documentation comment in .proto file."""

    def Status(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Doctor(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Liveness(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Readiness(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SubmitTask(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SubmitRemoteTask(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetTaskResult(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ClaimNextResultDelivery(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AckResultDelivery(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def FailResultDelivery(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def IngestRemoteResult(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ClaimTask(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ClaimNextTask(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Heartbeat(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CompleteTask(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def FailTask(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CancelTask(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def PutArtifact(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetArtifact(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListArtifacts(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteArtifact(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SendTask(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListPeers(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DiscoverSkills(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_KeryxDaemonServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Status': grpc.unary_unary_rpc_method_handler(
                    servicer.Status,
                    request_deserializer=hermes_dot_keryx_dot_v1_dot_daemon__pb2.StatusRequest.FromString,
                    response_serializer=hermes_dot_keryx_dot_v1_dot_daemon__pb2.StatusResponse.SerializeToString,
            ),
            'Doctor': grpc.unary_unary_rpc_method_handler(
                    servicer.Doctor,
                    request_deserializer=hermes_dot_keryx_dot_v1_dot_daemon__pb2.DoctorRequest.FromString,
                    response_serializer=hermes_dot_keryx_dot_v1_dot_daemon__pb2.DoctorResponse.SerializeToString,
            ),
            'Liveness': grpc.unary_unary_rpc_method_handler(
                    servicer.Liveness,
                    request_deserializer=hermes_dot_keryx_dot_v1_dot_daemon__pb2.LivenessRequest.FromString,
                    response_serializer=hermes_dot_keryx_dot_v1_dot_daemon__pb2.LivenessResponse.SerializeToString,
            ),
            'Readiness': grpc.unary_unary_rpc_method_handler(
                    servicer.Readiness,
                    request_deserializer=hermes_dot_keryx_dot_v1_dot_daemon__pb2.ReadinessRequest.FromString,
                    response_serializer=hermes_dot_keryx_dot_v1_dot_daemon__pb2.ReadinessResponse.SerializeToString,
            ),
            'SubmitTask': grpc.unary_unary_rpc_method_handler(
                    servicer.SubmitTask,
                    request_deserializer=hermes_dot_keryx_dot_v1_dot_daemon__pb2.SubmitTaskRequest.FromString,
                    response_serializer=hermes_dot_keryx_dot_v1_dot_daemon__pb2.SubmitTaskResponse.SerializeToString,
            ),
            'SubmitRemoteTask': grpc.unary_unary_rpc_method_handler(
                    servicer.SubmitRemoteTask,
                    request_deserializer=hermes_dot_keryx_dot_v1_dot_daemon__pb2.SubmitRemoteTaskRequest.FromString,
                    response_serializer=hermes_dot_keryx_dot_v1_dot_daemon__pb2.SubmitTaskResponse.SerializeToString,
            ),
            'GetTaskResult': grpc.unary_unary_rpc_method_handler(
                    servicer.GetTaskResult,
                    request_deserializer=hermes_dot_keryx_dot_v1_dot_daemon__pb2.GetTaskResultRequest.FromString,
                    response_serializer=hermes_dot_keryx_dot_v1_dot_daemon__pb2.GetTaskResultResponse.SerializeToString,
            ),
            'ClaimNextResultDelivery': grpc.unary_unary_rpc_method_handler(
                    servicer.ClaimNextResultDelivery,
                    request_deserializer=hermes_dot_keryx_dot_v1_dot_daemon__pb2.ClaimNextResultDeliveryRequest.FromString,
                    response_serializer=hermes_dot_keryx_dot_v1_dot_daemon__pb2.ClaimNextResultDeliveryResponse.SerializeToString,
            ),
            'AckResultDelivery': grpc.unary_unary_rpc_method_handler(
                    servicer.AckResultDelivery,
                    request_deserializer=hermes_dot_keryx_dot_v1_dot_daemon__pb2.AckResultDeliveryRequest.FromString,
                    response_serializer=hermes_dot_keryx_dot_v1_dot_daemon__pb2.AckResultDeliveryResponse.SerializeToString,
            ),
            'FailResultDelivery': grpc.unary_unary_rpc_method_handler(
                    servicer.FailResultDelivery,
                    request_deserializer=hermes_dot_keryx_dot_v1_dot_daemon__pb2.FailResultDeliveryRequest.FromString,
                    response_serializer=hermes_dot_keryx_dot_v1_dot_daemon__pb2.FailResultDeliveryResponse.SerializeToString,
            ),
            'IngestRemoteResult': grpc.unary_unary_rpc_method_handler(
                    servicer.IngestRemoteResult,
                    request_deserializer=hermes_dot_keryx_dot_v1_dot_daemon__pb2.IngestRemoteResultRequest.FromString,
                    response_serializer=hermes_dot_keryx_dot_v1_dot_daemon__pb2.IngestRemoteResultResponse.SerializeToString,
            ),
            'ClaimTask': grpc.unary_unary_rpc_method_handler(
                    servicer.ClaimTask,
                    request_deserializer=hermes_dot_keryx_dot_v1_dot_daemon__pb2.ClaimTaskRequest.FromString,
                    response_serializer=hermes_dot_keryx_dot_v1_dot_daemon__pb2.ClaimTaskResponse.SerializeToString,
            ),
            'ClaimNextTask': grpc.unary_unary_rpc_method_handler(
                    servicer.ClaimNextTask,
                    request_deserializer=hermes_dot_keryx_dot_v1_dot_daemon__pb2.ClaimNextTaskRequest.FromString,
                    response_serializer=hermes_dot_keryx_dot_v1_dot_daemon__pb2.ClaimNextTaskResponse.SerializeToString,
            ),
            'Heartbeat': grpc.unary_unary_rpc_method_handler(
                    servicer.Heartbeat,
                    request_deserializer=hermes_dot_keryx_dot_v1_dot_daemon__pb2.HeartbeatRequest.FromString,
                    response_serializer=hermes_dot_keryx_dot_v1_dot_daemon__pb2.HeartbeatResponse.SerializeToString,
            ),
            'CompleteTask': grpc.unary_unary_rpc_method_handler(
                    servicer.CompleteTask,
                    request_deserializer=hermes_dot_keryx_dot_v1_dot_daemon__pb2.CompleteTaskRequest.FromString,
                    response_serializer=hermes_dot_keryx_dot_v1_dot_daemon__pb2.CompleteTaskResponse.SerializeToString,
            ),
            'FailTask': grpc.unary_unary_rpc_method_handler(
                    servicer.FailTask,
                    request_deserializer=hermes_dot_keryx_dot_v1_dot_daemon__pb2.FailTaskRequest.FromString,
                    response_serializer=hermes_dot_keryx_dot_v1_dot_daemon__pb2.FailTaskResponse.SerializeToString,
            ),
            'CancelTask': grpc.unary_unary_rpc_method_handler(
                    servicer.CancelTask,
                    request_deserializer=hermes_dot_keryx_dot_v1_dot_daemon__pb2.CancelTaskRequest.FromString,
                    response_serializer=hermes_dot_keryx_dot_v1_dot_daemon__pb2.CancelTaskResponse.SerializeToString,
            ),
            'PutArtifact': grpc.unary_unary_rpc_method_handler(
                    servicer.PutArtifact,
                    request_deserializer=hermes_dot_keryx_dot_v1_dot_daemon__pb2.PutArtifactRequest.FromString,
                    response_serializer=hermes_dot_keryx_dot_v1_dot_daemon__pb2.PutArtifactResponse.SerializeToString,
            ),
            'GetArtifact': grpc.unary_unary_rpc_method_handler(
                    servicer.GetArtifact,
                    request_deserializer=hermes_dot_keryx_dot_v1_dot_daemon__pb2.GetArtifactRequest.FromString,
                    response_serializer=hermes_dot_keryx_dot_v1_dot_daemon__pb2.GetArtifactResponse.SerializeToString,
            ),
            'ListArtifacts': grpc.unary_unary_rpc_method_handler(
                    servicer.ListArtifacts,
                    request_deserializer=hermes_dot_keryx_dot_v1_dot_daemon__pb2.ListArtifactsRequest.FromString,
                    response_serializer=hermes_dot_keryx_dot_v1_dot_daemon__pb2.ListArtifactsResponse.SerializeToString,
            ),
            'DeleteArtifact': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteArtifact,
                    request_deserializer=hermes_dot_keryx_dot_v1_dot_daemon__pb2.DeleteArtifactRequest.FromString,
                    response_serializer=hermes_dot_keryx_dot_v1_dot_daemon__pb2.DeleteArtifactResponse.SerializeToString,
            ),
            'SendTask': grpc.unary_unary_rpc_method_handler(
                    servicer.SendTask,
                    request_deserializer=hermes_dot_keryx_dot_v1_dot_daemon__pb2.SendTaskRequest.FromString,
                    response_serializer=hermes_dot_keryx_dot_v1_dot_daemon__pb2.SendTaskResponse.SerializeToString,
            ),
            'ListPeers': grpc.unary_unary_rpc_method_handler(
                    servicer.ListPeers,
                    request_deserializer=hermes_dot_keryx_dot_v1_dot_daemon__pb2.ListPeersRequest.FromString,
                    response_serializer=hermes_dot_keryx_dot_v1_dot_daemon__pb2.ListPeersResponse.SerializeToString,
            ),
            'DiscoverSkills': grpc.unary_unary_rpc_method_handler(
                    servicer.DiscoverSkills,
                    request_deserializer=hermes_dot_keryx_dot_v1_dot_daemon__pb2.DiscoverSkillsRequest.FromString,
                    response_serializer=hermes_dot_keryx_dot_v1_dot_daemon__pb2.DiscoverSkillsResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'hermes.keryx.v1.KeryxDaemon', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('hermes.keryx.v1.KeryxDaemon', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class KeryxDaemon:
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Status(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/hermes.keryx.v1.KeryxDaemon/Status',
            hermes_dot_keryx_dot_v1_dot_daemon__pb2.StatusRequest.SerializeToString,
            hermes_dot_keryx_dot_v1_dot_daemon__pb2.StatusResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Doctor(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/hermes.keryx.v1.KeryxDaemon/Doctor',
            hermes_dot_keryx_dot_v1_dot_daemon__pb2.DoctorRequest.SerializeToString,
            hermes_dot_keryx_dot_v1_dot_daemon__pb2.DoctorResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Liveness(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/hermes.keryx.v1.KeryxDaemon/Liveness',
            hermes_dot_keryx_dot_v1_dot_daemon__pb2.LivenessRequest.SerializeToString,
            hermes_dot_keryx_dot_v1_dot_daemon__pb2.LivenessResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Readiness(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/hermes.keryx.v1.KeryxDaemon/Readiness',
            hermes_dot_keryx_dot_v1_dot_daemon__pb2.ReadinessRequest.SerializeToString,
            hermes_dot_keryx_dot_v1_dot_daemon__pb2.ReadinessResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SubmitTask(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/hermes.keryx.v1.KeryxDaemon/SubmitTask',
            hermes_dot_keryx_dot_v1_dot_daemon__pb2.SubmitTaskRequest.SerializeToString,
            hermes_dot_keryx_dot_v1_dot_daemon__pb2.SubmitTaskResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SubmitRemoteTask(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/hermes.keryx.v1.KeryxDaemon/SubmitRemoteTask',
            hermes_dot_keryx_dot_v1_dot_daemon__pb2.SubmitRemoteTaskRequest.SerializeToString,
            hermes_dot_keryx_dot_v1_dot_daemon__pb2.SubmitTaskResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetTaskResult(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/hermes.keryx.v1.KeryxDaemon/GetTaskResult',
            hermes_dot_keryx_dot_v1_dot_daemon__pb2.GetTaskResultRequest.SerializeToString,
            hermes_dot_keryx_dot_v1_dot_daemon__pb2.GetTaskResultResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ClaimNextResultDelivery(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/hermes.keryx.v1.KeryxDaemon/ClaimNextResultDelivery',
            hermes_dot_keryx_dot_v1_dot_daemon__pb2.ClaimNextResultDeliveryRequest.SerializeToString,
            hermes_dot_keryx_dot_v1_dot_daemon__pb2.ClaimNextResultDeliveryResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def AckResultDelivery(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/hermes.keryx.v1.KeryxDaemon/AckResultDelivery',
            hermes_dot_keryx_dot_v1_dot_daemon__pb2.AckResultDeliveryRequest.SerializeToString,
            hermes_dot_keryx_dot_v1_dot_daemon__pb2.AckResultDeliveryResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def FailResultDelivery(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/hermes.keryx.v1.KeryxDaemon/FailResultDelivery',
            hermes_dot_keryx_dot_v1_dot_daemon__pb2.FailResultDeliveryRequest.SerializeToString,
            hermes_dot_keryx_dot_v1_dot_daemon__pb2.FailResultDeliveryResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def IngestRemoteResult(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/hermes.keryx.v1.KeryxDaemon/IngestRemoteResult',
            hermes_dot_keryx_dot_v1_dot_daemon__pb2.IngestRemoteResultRequest.SerializeToString,
            hermes_dot_keryx_dot_v1_dot_daemon__pb2.IngestRemoteResultResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ClaimTask(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/hermes.keryx.v1.KeryxDaemon/ClaimTask',
            hermes_dot_keryx_dot_v1_dot_daemon__pb2.ClaimTaskRequest.SerializeToString,
            hermes_dot_keryx_dot_v1_dot_daemon__pb2.ClaimTaskResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ClaimNextTask(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/hermes.keryx.v1.KeryxDaemon/ClaimNextTask',
            hermes_dot_keryx_dot_v1_dot_daemon__pb2.ClaimNextTaskRequest.SerializeToString,
            hermes_dot_keryx_dot_v1_dot_daemon__pb2.ClaimNextTaskResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Heartbeat(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/hermes.keryx.v1.KeryxDaemon/Heartbeat',
            hermes_dot_keryx_dot_v1_dot_daemon__pb2.HeartbeatRequest.SerializeToString,
            hermes_dot_keryx_dot_v1_dot_daemon__pb2.HeartbeatResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CompleteTask(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/hermes.keryx.v1.KeryxDaemon/CompleteTask',
            hermes_dot_keryx_dot_v1_dot_daemon__pb2.CompleteTaskRequest.SerializeToString,
            hermes_dot_keryx_dot_v1_dot_daemon__pb2.CompleteTaskResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def FailTask(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/hermes.keryx.v1.KeryxDaemon/FailTask',
            hermes_dot_keryx_dot_v1_dot_daemon__pb2.FailTaskRequest.SerializeToString,
            hermes_dot_keryx_dot_v1_dot_daemon__pb2.FailTaskResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CancelTask(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/hermes.keryx.v1.KeryxDaemon/CancelTask',
            hermes_dot_keryx_dot_v1_dot_daemon__pb2.CancelTaskRequest.SerializeToString,
            hermes_dot_keryx_dot_v1_dot_daemon__pb2.CancelTaskResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def PutArtifact(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/hermes.keryx.v1.KeryxDaemon/PutArtifact',
            hermes_dot_keryx_dot_v1_dot_daemon__pb2.PutArtifactRequest.SerializeToString,
            hermes_dot_keryx_dot_v1_dot_daemon__pb2.PutArtifactResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetArtifact(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/hermes.keryx.v1.KeryxDaemon/GetArtifact',
            hermes_dot_keryx_dot_v1_dot_daemon__pb2.GetArtifactRequest.SerializeToString,
            hermes_dot_keryx_dot_v1_dot_daemon__pb2.GetArtifactResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListArtifacts(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/hermes.keryx.v1.KeryxDaemon/ListArtifacts',
            hermes_dot_keryx_dot_v1_dot_daemon__pb2.ListArtifactsRequest.SerializeToString,
            hermes_dot_keryx_dot_v1_dot_daemon__pb2.ListArtifactsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteArtifact(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/hermes.keryx.v1.KeryxDaemon/DeleteArtifact',
            hermes_dot_keryx_dot_v1_dot_daemon__pb2.DeleteArtifactRequest.SerializeToString,
            hermes_dot_keryx_dot_v1_dot_daemon__pb2.DeleteArtifactResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SendTask(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/hermes.keryx.v1.KeryxDaemon/SendTask',
            hermes_dot_keryx_dot_v1_dot_daemon__pb2.SendTaskRequest.SerializeToString,
            hermes_dot_keryx_dot_v1_dot_daemon__pb2.SendTaskResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListPeers(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/hermes.keryx.v1.KeryxDaemon/ListPeers',
            hermes_dot_keryx_dot_v1_dot_daemon__pb2.ListPeersRequest.SerializeToString,
            hermes_dot_keryx_dot_v1_dot_daemon__pb2.ListPeersResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DiscoverSkills(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/hermes.keryx.v1.KeryxDaemon/DiscoverSkills',
            hermes_dot_keryx_dot_v1_dot_daemon__pb2.DiscoverSkillsRequest.SerializeToString,
            hermes_dot_keryx_dot_v1_dot_daemon__pb2.DiscoverSkillsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
