# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: hermes/keryx/v1/event.proto
# Protobuf Python Version: 6.33.5
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    33,
    5,
    '',
    'hermes/keryx/v1/event.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from hermes.keryx.v1 import common_pb2 as hermes_dot_keryx_dot_v1_dot_common__pb2
from hermes.keryx.v1 import task_pb2 as hermes_dot_keryx_dot_v1_dot_task__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1bhermes/keryx/v1/event.proto\x12\x0fhermes.keryx.v1\x1a\x1chermes/keryx/v1/common.proto\x1a\x1ahermes/keryx/v1/task.proto\"\x86\x03\n\nKeryxEvent\x12\x10\n\x08\x65vent_id\x18\x01 \x01(\t\x12\x33\n\nevent_type\x18\x02 \x01(\x0e\x32\x1f.hermes.keryx.v1.KeryxEventType\x12(\n\x07task_id\x18\x03 \x01(\x0b\x32\x17.hermes.keryx.v1.TaskId\x12\x30\n\x0btask_status\x18\x04 \x01(\x0e\x32\x1b.hermes.keryx.v1.TaskStatus\x12\x36\n\x0e\x63orrelation_id\x18\x05 \x01(\x0b\x32\x1e.hermes.keryx.v1.CorrelationId\x12/\n\x0boccurred_at\x18\x06 \x01(\x0b\x32\x1a.hermes.keryx.v1.Timestamp\x12;\n\x08metadata\x18\x07 \x03(\x0b\x32).hermes.keryx.v1.KeryxEvent.MetadataEntry\x1a/\n\rMetadataEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01*\xd4\x04\n\x0eKeryxEventType\x12 \n\x1cKERYX_EVENT_TYPE_UNSPECIFIED\x10\x00\x12%\n!KERYX_EVENT_TYPE_AGENT_REGISTERED\x10\x01\x12$\n KERYX_EVENT_TYPE_AGENT_HEARTBEAT\x10\x02\x12\"\n\x1eKERYX_EVENT_TYPE_AGENT_OFFLINE\x10\x03\x12!\n\x1dKERYX_EVENT_TYPE_TASK_CREATED\x10\n\x12\"\n\x1eKERYX_EVENT_TYPE_TASK_ACCEPTED\x10\x0b\x12 \n\x1cKERYX_EVENT_TYPE_TASK_QUEUED\x10\x0c\x12 \n\x1cKERYX_EVENT_TYPE_TASK_LEASED\x10\r\x12!\n\x1dKERYX_EVENT_TYPE_TASK_STARTED\x10\x0e\x12#\n\x1fKERYX_EVENT_TYPE_TASK_COMPLETED\x10\x0f\x12 \n\x1cKERYX_EVENT_TYPE_TASK_FAILED\x10\x10\x12\"\n\x1eKERYX_EVENT_TYPE_TASK_CANCELED\x10\x11\x12#\n\x1fKERYX_EVENT_TYPE_TASK_TIMED_OUT\x10\x12\x12\'\n#KERYX_EVENT_TYPE_TASK_DEAD_LETTERED\x10\x13\x12\"\n\x1eKERYX_EVENT_TYPE_POLICY_DENIED\x10\x1e\x12$\n KERYX_EVENT_TYPE_RECOVERY_ACTION\x10(b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'hermes.keryx.v1.event_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_KERYXEVENT_METADATAENTRY']._loaded_options = None
  _globals['_KERYXEVENT_METADATAENTRY']._serialized_options = b'8\001'
  _globals['_KERYXEVENTTYPE']._serialized_start=500
  _globals['_KERYXEVENTTYPE']._serialized_end=1096
  _globals['_KERYXEVENT']._serialized_start=107
  _globals['_KERYXEVENT']._serialized_end=497
  _globals['_KERYXEVENT_METADATAENTRY']._serialized_start=450
  _globals['_KERYXEVENT_METADATAENTRY']._serialized_end=497
# @@protoc_insertion_point(module_scope)
