# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: hermes/keryx/v1/registry.proto
# Protobuf Python Version: 7.35.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    0,
    '',
    'hermes/keryx/v1/registry.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from hermes.keryx.v1 import common_pb2 as hermes_dot_keryx_dot_v1_dot_common__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1ehermes/keryx/v1/registry.proto\x12\x0fhermes.keryx.v1\x1a\x1chermes/keryx/v1/common.proto\"@\n\tSkillInfo\x12\x10\n\x08skill_id\x18\x01 \x01(\t\x12\x13\n\x0b\x64\x65scription\x18\x02 \x01(\t\x12\x0c\n\x04tags\x18\x03 \x03(\t\"\x9e\x01\n\x0cRegistration\x12\x0f\n\x07peer_id\x18\x01 \x01(\t\x12*\n\x06skills\x18\x02 \x03(\x0b\x32\x1a.hermes.keryx.v1.SkillInfo\x12\x0c\n\x04name\x18\x03 \x01(\t\x12\x13\n\x0b\x64\x65scription\x18\x04 \x01(\t\x12.\n\nexpires_at\x18\x05 \x01(\x0b\x32\x1a.hermes.keryx.v1.Timestamp\"\x8c\x01\n\x15RegisterSkillsRequest\x12\x0f\n\x07peer_id\x18\x01 \x01(\t\x12*\n\x06skills\x18\x02 \x03(\x0b\x32\x1a.hermes.keryx.v1.SkillInfo\x12\x0c\n\x04name\x18\x03 \x01(\t\x12\x13\n\x0b\x64\x65scription\x18\x04 \x01(\t\x12\x13\n\x0bttl_seconds\x18\x05 \x01(\x04\"*\n\x16RegisterSkillsResponse\x12\x10\n\x08\x61\x63\x63\x65pted\x18\x01 \x01(\x08\"=\n\x17UnregisterSkillsRequest\x12\x0f\n\x07peer_id\x18\x01 \x01(\t\x12\x11\n\tskill_ids\x18\x02 \x03(\t\",\n\x18UnregisterSkillsResponse\x12\x10\n\x08\x61\x63\x63\x65pted\x18\x01 \x01(\x08\"G\n\x16\x44iscoverBySkillRequest\x12\x10\n\x08skill_id\x18\x01 \x01(\t\x12\x0c\n\x04tags\x18\x02 \x03(\t\x12\r\n\x05limit\x18\x03 \x01(\r\"O\n\x17\x44iscoverBySkillResponse\x12\x34\n\rregistrations\x18\x01 \x03(\x0b\x32\x1d.hermes.keryx.v1.Registration2\xc3\x02\n\x0fRegistryService\x12\x61\n\x0eRegisterSkills\x12&.hermes.keryx.v1.RegisterSkillsRequest\x1a\'.hermes.keryx.v1.RegisterSkillsResponse\x12g\n\x10UnregisterSkills\x12(.hermes.keryx.v1.UnregisterSkillsRequest\x1a).hermes.keryx.v1.UnregisterSkillsResponse\x12\x64\n\x0f\x44iscoverBySkill\x12\'.hermes.keryx.v1.DiscoverBySkillRequest\x1a(.hermes.keryx.v1.DiscoverBySkillResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'hermes.keryx.v1.registry_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_SKILLINFO']._serialized_start=81
  _globals['_SKILLINFO']._serialized_end=145
  _globals['_REGISTRATION']._serialized_start=148
  _globals['_REGISTRATION']._serialized_end=306
  _globals['_REGISTERSKILLSREQUEST']._serialized_start=309
  _globals['_REGISTERSKILLSREQUEST']._serialized_end=449
  _globals['_REGISTERSKILLSRESPONSE']._serialized_start=451
  _globals['_REGISTERSKILLSRESPONSE']._serialized_end=493
  _globals['_UNREGISTERSKILLSREQUEST']._serialized_start=495
  _globals['_UNREGISTERSKILLSREQUEST']._serialized_end=556
  _globals['_UNREGISTERSKILLSRESPONSE']._serialized_start=558
  _globals['_UNREGISTERSKILLSRESPONSE']._serialized_end=602
  _globals['_DISCOVERBYSKILLREQUEST']._serialized_start=604
  _globals['_DISCOVERBYSKILLREQUEST']._serialized_end=675
  _globals['_DISCOVERBYSKILLRESPONSE']._serialized_start=677
  _globals['_DISCOVERBYSKILLRESPONSE']._serialized_end=756
  _globals['_REGISTRYSERVICE']._serialized_start=759
  _globals['_REGISTRYSERVICE']._serialized_end=1082
# @@protoc_insertion_point(module_scope)
