# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: hermes/keryx/v1/relay.proto
# Protobuf Python Version: 7.35.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    0,
    '',
    'hermes/keryx/v1/relay.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from hermes.keryx.v1 import common_pb2 as hermes_dot_keryx_dot_v1_dot_common__pb2
from hermes.keryx.v1 import task_pb2 as hermes_dot_keryx_dot_v1_dot_task__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1bhermes/keryx/v1/relay.proto\x12\x0fhermes.keryx.v1\x1a\x1chermes/keryx/v1/common.proto\x1a\x1ahermes/keryx/v1/task.proto\"\x0f\n\rHealthRequest\"\xb0\x01\n\x0eHealthResponse\x12\x0f\n\x07healthy\x18\x01 \x01(\x08\x12\x17\n\x0f\x63onnected_peers\x18\x02 \x01(\x04\x12\x15\n\rregistry_size\x18\x03 \x01(\x04\x12\x16\n\x0euptime_seconds\x18\x04 \x01(\x04\x12\x18\n\x10transport_status\x18\x05 \x01(\t\x12\x14\n\x0ctasks_routed\x18\x06 \x01(\x04\x12\x15\n\rlocal_peer_id\x18\x07 \x01(\t\"J\n\tNodeFrame\x12\x10\n\x08\x66rame_id\x18\x01 \x01(\t\x12+\n\x04task\x18\x02 \x01(\x0b\x32\x1d.hermes.keryx.v1.TaskEnvelope\"K\n\nRelayFrame\x12\x10\n\x08\x66rame_id\x18\x01 \x01(\t\x12+\n\x04task\x18\x02 \x01(\x0b\x32\x1d.hermes.keryx.v1.TaskEnvelope\"N\n\x13RegisterNodeRequest\x12(\n\x07node_id\x18\x01 \x01(\x0b\x32\x17.hermes.keryx.v1.NodeId\x12\r\n\x05token\x18\x02 \x01(\t\"(\n\x14RegisterNodeResponse\x12\x10\n\x08\x61\x63\x63\x65pted\x18\x01 \x01(\x08\"A\n\x12PublishTaskRequest\x12+\n\x04task\x18\x01 \x01(\x0b\x32\x1d.hermes.keryx.v1.TaskEnvelope\"?\n\x13PublishTaskResponse\x12(\n\x07task_id\x18\x01 \x01(\x0b\x32\x17.hermes.keryx.v1.TaskId\":\n\x0e\x41\x63kTaskRequest\x12(\n\x07task_id\x18\x01 \x01(\x0b\x32\x17.hermes.keryx.v1.TaskId\"#\n\x0f\x41\x63kTaskResponse\x12\x10\n\x08\x61\x63\x63\x65pted\x18\x01 \x01(\x08\x32\xa8\x03\n\nKeryxRelay\x12J\n\x0b\x43onnectNode\x12\x1a.hermes.keryx.v1.NodeFrame\x1a\x1b.hermes.keryx.v1.RelayFrame(\x01\x30\x01\x12[\n\x0cRegisterNode\x12$.hermes.keryx.v1.RegisterNodeRequest\x1a%.hermes.keryx.v1.RegisterNodeResponse\x12X\n\x0bPublishTask\x12#.hermes.keryx.v1.PublishTaskRequest\x1a$.hermes.keryx.v1.PublishTaskResponse\x12L\n\x07\x41\x63kTask\x12\x1f.hermes.keryx.v1.AckTaskRequest\x1a .hermes.keryx.v1.AckTaskResponse\x12I\n\x06Health\x12\x1e.hermes.keryx.v1.HealthRequest\x1a\x1f.hermes.keryx.v1.HealthResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'hermes.keryx.v1.relay_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_HEALTHREQUEST']._serialized_start=106
  _globals['_HEALTHREQUEST']._serialized_end=121
  _globals['_HEALTHRESPONSE']._serialized_start=124
  _globals['_HEALTHRESPONSE']._serialized_end=300
  _globals['_NODEFRAME']._serialized_start=302
  _globals['_NODEFRAME']._serialized_end=376
  _globals['_RELAYFRAME']._serialized_start=378
  _globals['_RELAYFRAME']._serialized_end=453
  _globals['_REGISTERNODEREQUEST']._serialized_start=455
  _globals['_REGISTERNODEREQUEST']._serialized_end=533
  _globals['_REGISTERNODERESPONSE']._serialized_start=535
  _globals['_REGISTERNODERESPONSE']._serialized_end=575
  _globals['_PUBLISHTASKREQUEST']._serialized_start=577
  _globals['_PUBLISHTASKREQUEST']._serialized_end=642
  _globals['_PUBLISHTASKRESPONSE']._serialized_start=644
  _globals['_PUBLISHTASKRESPONSE']._serialized_end=707
  _globals['_ACKTASKREQUEST']._serialized_start=709
  _globals['_ACKTASKREQUEST']._serialized_end=767
  _globals['_ACKTASKRESPONSE']._serialized_start=769
  _globals['_ACKTASKRESPONSE']._serialized_end=804
  _globals['_KERYXRELAY']._serialized_start=807
  _globals['_KERYXRELAY']._serialized_end=1231
# @@protoc_insertion_point(module_scope)
