# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from hermes.keryx.v1 import relay_pb2 as hermes_dot_keryx_dot_v1_dot_relay__pb2

GRPC_GENERATED_VERSION = '1.82.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in hermes/keryx/v1/relay_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class KeryxRelayStub:
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ConnectNode = channel.stream_stream(
                '/hermes.keryx.v1.KeryxRelay/ConnectNode',
                request_serializer=hermes_dot_keryx_dot_v1_dot_relay__pb2.NodeFrame.SerializeToString,
                response_deserializer=hermes_dot_keryx_dot_v1_dot_relay__pb2.RelayFrame.FromString,
                _registered_method=True)
        self.RegisterNode = channel.unary_unary(
                '/hermes.keryx.v1.KeryxRelay/RegisterNode',
                request_serializer=hermes_dot_keryx_dot_v1_dot_relay__pb2.RegisterNodeRequest.SerializeToString,
                response_deserializer=hermes_dot_keryx_dot_v1_dot_relay__pb2.RegisterNodeResponse.FromString,
                _registered_method=True)
        self.PublishTask = channel.unary_unary(
                '/hermes.keryx.v1.KeryxRelay/PublishTask',
                request_serializer=hermes_dot_keryx_dot_v1_dot_relay__pb2.PublishTaskRequest.SerializeToString,
                response_deserializer=hermes_dot_keryx_dot_v1_dot_relay__pb2.PublishTaskResponse.FromString,
                _registered_method=True)
        self.AckTask = channel.unary_unary(
                '/hermes.keryx.v1.KeryxRelay/AckTask',
                request_serializer=hermes_dot_keryx_dot_v1_dot_relay__pb2.AckTaskRequest.SerializeToString,
                response_deserializer=hermes_dot_keryx_dot_v1_dot_relay__pb2.AckTaskResponse.FromString,
                _registered_method=True)
        self.Health = channel.unary_unary(
                '/hermes.keryx.v1.KeryxRelay/Health',
                request_serializer=hermes_dot_keryx_dot_v1_dot_relay__pb2.HealthRequest.SerializeToString,
                response_deserializer=hermes_dot_keryx_dot_v1_dot_relay__pb2.HealthResponse.FromString,
                _registered_method=True)


class KeryxRelayServicer:
    """Missing associated documentation comment in .proto file."""

    def ConnectNode(self, request_iterator, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RegisterNode(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def PublishTask(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AckTask(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Health(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_KeryxRelayServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ConnectNode': grpc.stream_stream_rpc_method_handler(
                    servicer.ConnectNode,
                    request_deserializer=hermes_dot_keryx_dot_v1_dot_relay__pb2.NodeFrame.FromString,
                    response_serializer=hermes_dot_keryx_dot_v1_dot_relay__pb2.RelayFrame.SerializeToString,
            ),
            'RegisterNode': grpc.unary_unary_rpc_method_handler(
                    servicer.RegisterNode,
                    request_deserializer=hermes_dot_keryx_dot_v1_dot_relay__pb2.RegisterNodeRequest.FromString,
                    response_serializer=hermes_dot_keryx_dot_v1_dot_relay__pb2.RegisterNodeResponse.SerializeToString,
            ),
            'PublishTask': grpc.unary_unary_rpc_method_handler(
                    servicer.PublishTask,
                    request_deserializer=hermes_dot_keryx_dot_v1_dot_relay__pb2.PublishTaskRequest.FromString,
                    response_serializer=hermes_dot_keryx_dot_v1_dot_relay__pb2.PublishTaskResponse.SerializeToString,
            ),
            'AckTask': grpc.unary_unary_rpc_method_handler(
                    servicer.AckTask,
                    request_deserializer=hermes_dot_keryx_dot_v1_dot_relay__pb2.AckTaskRequest.FromString,
                    response_serializer=hermes_dot_keryx_dot_v1_dot_relay__pb2.AckTaskResponse.SerializeToString,
            ),
            'Health': grpc.unary_unary_rpc_method_handler(
                    servicer.Health,
                    request_deserializer=hermes_dot_keryx_dot_v1_dot_relay__pb2.HealthRequest.FromString,
                    response_serializer=hermes_dot_keryx_dot_v1_dot_relay__pb2.HealthResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'hermes.keryx.v1.KeryxRelay', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('hermes.keryx.v1.KeryxRelay', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class KeryxRelay:
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def ConnectNode(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(
            request_iterator,
            target,
            '/hermes.keryx.v1.KeryxRelay/ConnectNode',
            hermes_dot_keryx_dot_v1_dot_relay__pb2.NodeFrame.SerializeToString,
            hermes_dot_keryx_dot_v1_dot_relay__pb2.RelayFrame.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RegisterNode(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/hermes.keryx.v1.KeryxRelay/RegisterNode',
            hermes_dot_keryx_dot_v1_dot_relay__pb2.RegisterNodeRequest.SerializeToString,
            hermes_dot_keryx_dot_v1_dot_relay__pb2.RegisterNodeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def PublishTask(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/hermes.keryx.v1.KeryxRelay/PublishTask',
            hermes_dot_keryx_dot_v1_dot_relay__pb2.PublishTaskRequest.SerializeToString,
            hermes_dot_keryx_dot_v1_dot_relay__pb2.PublishTaskResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def AckTask(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/hermes.keryx.v1.KeryxRelay/AckTask',
            hermes_dot_keryx_dot_v1_dot_relay__pb2.AckTaskRequest.SerializeToString,
            hermes_dot_keryx_dot_v1_dot_relay__pb2.AckTaskResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Health(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/hermes.keryx.v1.KeryxRelay/Health',
            hermes_dot_keryx_dot_v1_dot_relay__pb2.HealthRequest.SerializeToString,
            hermes_dot_keryx_dot_v1_dot_relay__pb2.HealthResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
