# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from hermes.keryx.v1 import relay_pb2 as hermes_dot_keryx_dot_v1_dot_relay__pb2

GRPC_GENERATED_VERSION = '1.83.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in hermes/keryx/v1/relay_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class KeryxRelayStub:
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ConnectNode = channel.stream_stream(
                '/hermes.keryx.v1.KeryxRelay/ConnectNode',
                request_serializer=hermes_dot_keryx_dot_v1_dot_relay__pb2.NodeFrame.SerializeToString,
                response_deserializer=hermes_dot_keryx_dot_v1_dot_relay__pb2.RelayFrame.FromString,
                _registered_method=True)
        self.RegisterNode = channel.unary_unary(
                '/hermes.keryx.v1.KeryxRelay/RegisterNode',
                request_serializer=hermes_dot_keryx_dot_v1_dot_relay__pb2.RegisterNodeRequest.SerializeToString,
                response_deserializer=hermes_dot_keryx_dot_v1_dot_relay__pb2.RegisterNodeResponse.FromString,
                _registered_method=True)
        self.PublishTask = channel.unary_unary(
                '/hermes.keryx.v1.KeryxRelay/PublishTask',
                request_serializer=hermes_dot_keryx_dot_v1_dot_relay__pb2.PublishTaskRequest.SerializeToString,
                response_deserializer=hermes_dot_keryx_dot_v1_dot_relay__pb2.PublishTaskResponse.FromString,
                _registered_method=True)
        self.PublishResult = channel.unary_unary(
                '/hermes.keryx.v1.KeryxRelay/PublishResult',
                request_serializer=hermes_dot_keryx_dot_v1_dot_relay__pb2.PublishResultRequest.SerializeToString,
                response_deserializer=hermes_dot_keryx_dot_v1_dot_relay__pb2.PublishResultResponse.FromString,
                _registered_method=True)
        self.PublishNodescaleIdentityBind = channel.unary_unary(
                '/hermes.keryx.v1.KeryxRelay/PublishNodescaleIdentityBind',
                request_serializer=hermes_dot_keryx_dot_v1_dot_relay__pb2.PublishNodescaleIdentityBindRequest.SerializeToString,
                response_deserializer=hermes_dot_keryx_dot_v1_dot_relay__pb2.PublishNodescaleIdentityBindResponse.FromString,
                _registered_method=True)
        self.PublishNodescaleIdentityBindV2 = channel.unary_unary(
                '/hermes.keryx.v1.KeryxRelay/PublishNodescaleIdentityBindV2',
                request_serializer=hermes_dot_keryx_dot_v1_dot_relay__pb2.PublishNodescaleIdentityBindV2Request.SerializeToString,
                response_deserializer=hermes_dot_keryx_dot_v1_dot_relay__pb2.PublishNodescaleIdentityBindResponse.FromString,
                _registered_method=True)
        self.CompleteNodescaleIdentityBind = channel.unary_unary(
                '/hermes.keryx.v1.KeryxRelay/CompleteNodescaleIdentityBind',
                request_serializer=hermes_dot_keryx_dot_v1_dot_relay__pb2.CompleteNodescaleIdentityBindRequest.SerializeToString,
                response_deserializer=hermes_dot_keryx_dot_v1_dot_relay__pb2.CompleteNodescaleIdentityBindResponse.FromString,
                _registered_method=True)
        self.PublishNodescaleIdentityChallenge = channel.unary_unary(
                '/hermes.keryx.v1.KeryxRelay/PublishNodescaleIdentityChallenge',
                request_serializer=hermes_dot_keryx_dot_v1_dot_relay__pb2.PublishNodescaleIdentityChallengeRequest.SerializeToString,
                response_deserializer=hermes_dot_keryx_dot_v1_dot_relay__pb2.PublishNodescaleIdentityChallengeResponse.FromString,
                _registered_method=True)
        self.PublishNodescaleIdentityChallengeV2 = channel.unary_unary(
                '/hermes.keryx.v1.KeryxRelay/PublishNodescaleIdentityChallengeV2',
                request_serializer=hermes_dot_keryx_dot_v1_dot_relay__pb2.PublishNodescaleIdentityChallengeV2Request.SerializeToString,
                response_deserializer=hermes_dot_keryx_dot_v1_dot_relay__pb2.PublishNodescaleIdentityChallengeResponse.FromString,
                _registered_method=True)
        self.CompleteNodescaleIdentityChallenge = channel.unary_unary(
                '/hermes.keryx.v1.KeryxRelay/CompleteNodescaleIdentityChallenge',
                request_serializer=hermes_dot_keryx_dot_v1_dot_relay__pb2.CompleteNodescaleIdentityChallengeRequest.SerializeToString,
                response_deserializer=hermes_dot_keryx_dot_v1_dot_relay__pb2.CompleteNodescaleIdentityChallengeResponse.FromString,
                _registered_method=True)
        self.PublishFleetObservation = channel.unary_unary(
                '/hermes.keryx.v1.KeryxRelay/PublishFleetObservation',
                request_serializer=hermes_dot_keryx_dot_v1_dot_relay__pb2.PublishFleetObservationRequest.SerializeToString,
                response_deserializer=hermes_dot_keryx_dot_v1_dot_relay__pb2.PublishFleetObservationResponse.FromString,
                _registered_method=True)
        self.CompleteFleetObservation = channel.unary_unary(
                '/hermes.keryx.v1.KeryxRelay/CompleteFleetObservation',
                request_serializer=hermes_dot_keryx_dot_v1_dot_relay__pb2.CompleteFleetObservationRequest.SerializeToString,
                response_deserializer=hermes_dot_keryx_dot_v1_dot_relay__pb2.CompleteFleetObservationResponse.FromString,
                _registered_method=True)
        self.AckTask = channel.unary_unary(
                '/hermes.keryx.v1.KeryxRelay/AckTask',
                request_serializer=hermes_dot_keryx_dot_v1_dot_relay__pb2.AckTaskRequest.SerializeToString,
                response_deserializer=hermes_dot_keryx_dot_v1_dot_relay__pb2.AckTaskResponse.FromString,
                _registered_method=True)
        self.AckFrame = channel.unary_unary(
                '/hermes.keryx.v1.KeryxRelay/AckFrame',
                request_serializer=hermes_dot_keryx_dot_v1_dot_relay__pb2.AckFrameRequest.SerializeToString,
                response_deserializer=hermes_dot_keryx_dot_v1_dot_relay__pb2.AckFrameResponse.FromString,
                _registered_method=True)
        self.Health = channel.unary_unary(
                '/hermes.keryx.v1.KeryxRelay/Health',
                request_serializer=hermes_dot_keryx_dot_v1_dot_relay__pb2.HealthRequest.SerializeToString,
                response_deserializer=hermes_dot_keryx_dot_v1_dot_relay__pb2.HealthResponse.FromString,
                _registered_method=True)


class KeryxRelayServicer:
    """Missing associated documentation comment in .proto file."""

    def ConnectNode(self, request_iterator, context):
        """Receive-only delivery stream. Task/result mutation frames sent by clients are rejected;
        use the authenticated unary PublishTask and PublishResult RPCs instead.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RegisterNode(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def PublishTask(self, request, context):
        """Authenticated unary task publication.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def PublishResult(self, request, context):
        """Authenticated unary terminal-result publication. Success is returned only after the
        authenticated destination persists the result and acknowledges the relay-issued frame.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def PublishNodescaleIdentityBind(self, request, context):
        """Typed non-execution relay-to-edge control. Source identity is metadata-only.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def PublishNodescaleIdentityBindV2(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CompleteNodescaleIdentityBind(self, request, context):
        """Destination-only typed completion for a relay-issued control frame.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def PublishNodescaleIdentityChallenge(self, request, context):
        """Typed non-execution challenge issuance. Source identity is metadata-only. This is
        authenticated at-least-once transport: the installed Nodescale handler, not Keryx,
        must durably deduplicate `(authenticated_sender_peer_id, operation_id)`.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def PublishNodescaleIdentityChallengeV2(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CompleteNodescaleIdentityChallenge(self, request, context):
        """Destination-only typed challenge completion for a relay-issued control frame.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def PublishFleetObservation(self, request, context):
        """Internal non-execution Fleet observation control. The body is either an
        acquire(selector-only) request or a publish(epoch plus bounded sample).
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CompleteFleetObservation(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AckTask(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AckFrame(self, request, context):
        """Destination-owned acknowledgement; the authenticated caller must own the relay frame.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Health(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_KeryxRelayServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ConnectNode': grpc.stream_stream_rpc_method_handler(
                    servicer.ConnectNode,
                    request_deserializer=hermes_dot_keryx_dot_v1_dot_relay__pb2.NodeFrame.FromString,
                    response_serializer=hermes_dot_keryx_dot_v1_dot_relay__pb2.RelayFrame.SerializeToString,
            ),
            'RegisterNode': grpc.unary_unary_rpc_method_handler(
                    servicer.RegisterNode,
                    request_deserializer=hermes_dot_keryx_dot_v1_dot_relay__pb2.RegisterNodeRequest.FromString,
                    response_serializer=hermes_dot_keryx_dot_v1_dot_relay__pb2.RegisterNodeResponse.SerializeToString,
            ),
            'PublishTask': grpc.unary_unary_rpc_method_handler(
                    servicer.PublishTask,
                    request_deserializer=hermes_dot_keryx_dot_v1_dot_relay__pb2.PublishTaskRequest.FromString,
                    response_serializer=hermes_dot_keryx_dot_v1_dot_relay__pb2.PublishTaskResponse.SerializeToString,
            ),
            'PublishResult': grpc.unary_unary_rpc_method_handler(
                    servicer.PublishResult,
                    request_deserializer=hermes_dot_keryx_dot_v1_dot_relay__pb2.PublishResultRequest.FromString,
                    response_serializer=hermes_dot_keryx_dot_v1_dot_relay__pb2.PublishResultResponse.SerializeToString,
            ),
            'PublishNodescaleIdentityBind': grpc.unary_unary_rpc_method_handler(
                    servicer.PublishNodescaleIdentityBind,
                    request_deserializer=hermes_dot_keryx_dot_v1_dot_relay__pb2.PublishNodescaleIdentityBindRequest.FromString,
                    response_serializer=hermes_dot_keryx_dot_v1_dot_relay__pb2.PublishNodescaleIdentityBindResponse.SerializeToString,
            ),
            'PublishNodescaleIdentityBindV2': grpc.unary_unary_rpc_method_handler(
                    servicer.PublishNodescaleIdentityBindV2,
                    request_deserializer=hermes_dot_keryx_dot_v1_dot_relay__pb2.PublishNodescaleIdentityBindV2Request.FromString,
                    response_serializer=hermes_dot_keryx_dot_v1_dot_relay__pb2.PublishNodescaleIdentityBindResponse.SerializeToString,
            ),
            'CompleteNodescaleIdentityBind': grpc.unary_unary_rpc_method_handler(
                    servicer.CompleteNodescaleIdentityBind,
                    request_deserializer=hermes_dot_keryx_dot_v1_dot_relay__pb2.CompleteNodescaleIdentityBindRequest.FromString,
                    response_serializer=hermes_dot_keryx_dot_v1_dot_relay__pb2.CompleteNodescaleIdentityBindResponse.SerializeToString,
            ),
            'PublishNodescaleIdentityChallenge': grpc.unary_unary_rpc_method_handler(
                    servicer.PublishNodescaleIdentityChallenge,
                    request_deserializer=hermes_dot_keryx_dot_v1_dot_relay__pb2.PublishNodescaleIdentityChallengeRequest.FromString,
                    response_serializer=hermes_dot_keryx_dot_v1_dot_relay__pb2.PublishNodescaleIdentityChallengeResponse.SerializeToString,
            ),
            'PublishNodescaleIdentityChallengeV2': grpc.unary_unary_rpc_method_handler(
                    servicer.PublishNodescaleIdentityChallengeV2,
                    request_deserializer=hermes_dot_keryx_dot_v1_dot_relay__pb2.PublishNodescaleIdentityChallengeV2Request.FromString,
                    response_serializer=hermes_dot_keryx_dot_v1_dot_relay__pb2.PublishNodescaleIdentityChallengeResponse.SerializeToString,
            ),
            'CompleteNodescaleIdentityChallenge': grpc.unary_unary_rpc_method_handler(
                    servicer.CompleteNodescaleIdentityChallenge,
                    request_deserializer=hermes_dot_keryx_dot_v1_dot_relay__pb2.CompleteNodescaleIdentityChallengeRequest.FromString,
                    response_serializer=hermes_dot_keryx_dot_v1_dot_relay__pb2.CompleteNodescaleIdentityChallengeResponse.SerializeToString,
            ),
            'PublishFleetObservation': grpc.unary_unary_rpc_method_handler(
                    servicer.PublishFleetObservation,
                    request_deserializer=hermes_dot_keryx_dot_v1_dot_relay__pb2.PublishFleetObservationRequest.FromString,
                    response_serializer=hermes_dot_keryx_dot_v1_dot_relay__pb2.PublishFleetObservationResponse.SerializeToString,
            ),
            'CompleteFleetObservation': grpc.unary_unary_rpc_method_handler(
                    servicer.CompleteFleetObservation,
                    request_deserializer=hermes_dot_keryx_dot_v1_dot_relay__pb2.CompleteFleetObservationRequest.FromString,
                    response_serializer=hermes_dot_keryx_dot_v1_dot_relay__pb2.CompleteFleetObservationResponse.SerializeToString,
            ),
            'AckTask': grpc.unary_unary_rpc_method_handler(
                    servicer.AckTask,
                    request_deserializer=hermes_dot_keryx_dot_v1_dot_relay__pb2.AckTaskRequest.FromString,
                    response_serializer=hermes_dot_keryx_dot_v1_dot_relay__pb2.AckTaskResponse.SerializeToString,
            ),
            'AckFrame': grpc.unary_unary_rpc_method_handler(
                    servicer.AckFrame,
                    request_deserializer=hermes_dot_keryx_dot_v1_dot_relay__pb2.AckFrameRequest.FromString,
                    response_serializer=hermes_dot_keryx_dot_v1_dot_relay__pb2.AckFrameResponse.SerializeToString,
            ),
            'Health': grpc.unary_unary_rpc_method_handler(
                    servicer.Health,
                    request_deserializer=hermes_dot_keryx_dot_v1_dot_relay__pb2.HealthRequest.FromString,
                    response_serializer=hermes_dot_keryx_dot_v1_dot_relay__pb2.HealthResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'hermes.keryx.v1.KeryxRelay', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('hermes.keryx.v1.KeryxRelay', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class KeryxRelay:
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def ConnectNode(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(
            request_iterator,
            target,
            '/hermes.keryx.v1.KeryxRelay/ConnectNode',
            hermes_dot_keryx_dot_v1_dot_relay__pb2.NodeFrame.SerializeToString,
            hermes_dot_keryx_dot_v1_dot_relay__pb2.RelayFrame.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RegisterNode(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/hermes.keryx.v1.KeryxRelay/RegisterNode',
            hermes_dot_keryx_dot_v1_dot_relay__pb2.RegisterNodeRequest.SerializeToString,
            hermes_dot_keryx_dot_v1_dot_relay__pb2.RegisterNodeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def PublishTask(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/hermes.keryx.v1.KeryxRelay/PublishTask',
            hermes_dot_keryx_dot_v1_dot_relay__pb2.PublishTaskRequest.SerializeToString,
            hermes_dot_keryx_dot_v1_dot_relay__pb2.PublishTaskResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def PublishResult(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/hermes.keryx.v1.KeryxRelay/PublishResult',
            hermes_dot_keryx_dot_v1_dot_relay__pb2.PublishResultRequest.SerializeToString,
            hermes_dot_keryx_dot_v1_dot_relay__pb2.PublishResultResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def PublishNodescaleIdentityBind(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/hermes.keryx.v1.KeryxRelay/PublishNodescaleIdentityBind',
            hermes_dot_keryx_dot_v1_dot_relay__pb2.PublishNodescaleIdentityBindRequest.SerializeToString,
            hermes_dot_keryx_dot_v1_dot_relay__pb2.PublishNodescaleIdentityBindResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def PublishNodescaleIdentityBindV2(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/hermes.keryx.v1.KeryxRelay/PublishNodescaleIdentityBindV2',
            hermes_dot_keryx_dot_v1_dot_relay__pb2.PublishNodescaleIdentityBindV2Request.SerializeToString,
            hermes_dot_keryx_dot_v1_dot_relay__pb2.PublishNodescaleIdentityBindResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CompleteNodescaleIdentityBind(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/hermes.keryx.v1.KeryxRelay/CompleteNodescaleIdentityBind',
            hermes_dot_keryx_dot_v1_dot_relay__pb2.CompleteNodescaleIdentityBindRequest.SerializeToString,
            hermes_dot_keryx_dot_v1_dot_relay__pb2.CompleteNodescaleIdentityBindResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def PublishNodescaleIdentityChallenge(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/hermes.keryx.v1.KeryxRelay/PublishNodescaleIdentityChallenge',
            hermes_dot_keryx_dot_v1_dot_relay__pb2.PublishNodescaleIdentityChallengeRequest.SerializeToString,
            hermes_dot_keryx_dot_v1_dot_relay__pb2.PublishNodescaleIdentityChallengeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def PublishNodescaleIdentityChallengeV2(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/hermes.keryx.v1.KeryxRelay/PublishNodescaleIdentityChallengeV2',
            hermes_dot_keryx_dot_v1_dot_relay__pb2.PublishNodescaleIdentityChallengeV2Request.SerializeToString,
            hermes_dot_keryx_dot_v1_dot_relay__pb2.PublishNodescaleIdentityChallengeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CompleteNodescaleIdentityChallenge(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/hermes.keryx.v1.KeryxRelay/CompleteNodescaleIdentityChallenge',
            hermes_dot_keryx_dot_v1_dot_relay__pb2.CompleteNodescaleIdentityChallengeRequest.SerializeToString,
            hermes_dot_keryx_dot_v1_dot_relay__pb2.CompleteNodescaleIdentityChallengeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def PublishFleetObservation(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/hermes.keryx.v1.KeryxRelay/PublishFleetObservation',
            hermes_dot_keryx_dot_v1_dot_relay__pb2.PublishFleetObservationRequest.SerializeToString,
            hermes_dot_keryx_dot_v1_dot_relay__pb2.PublishFleetObservationResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CompleteFleetObservation(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/hermes.keryx.v1.KeryxRelay/CompleteFleetObservation',
            hermes_dot_keryx_dot_v1_dot_relay__pb2.CompleteFleetObservationRequest.SerializeToString,
            hermes_dot_keryx_dot_v1_dot_relay__pb2.CompleteFleetObservationResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def AckTask(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/hermes.keryx.v1.KeryxRelay/AckTask',
            hermes_dot_keryx_dot_v1_dot_relay__pb2.AckTaskRequest.SerializeToString,
            hermes_dot_keryx_dot_v1_dot_relay__pb2.AckTaskResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def AckFrame(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/hermes.keryx.v1.KeryxRelay/AckFrame',
            hermes_dot_keryx_dot_v1_dot_relay__pb2.AckFrameRequest.SerializeToString,
            hermes_dot_keryx_dot_v1_dot_relay__pb2.AckFrameResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Health(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/hermes.keryx.v1.KeryxRelay/Health',
            hermes_dot_keryx_dot_v1_dot_relay__pb2.HealthRequest.SerializeToString,
            hermes_dot_keryx_dot_v1_dot_relay__pb2.HealthResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
